virtru/virtuoso-design-system

.autorc
.gitignore
commitlint.config.js
jest.config.js
lefthook.yml
lib/helpers/expandChildren.js
lib/helpers/expandChildren.test.js
package-lock.json
package.json

- add linters and lefthook
- update build dirs

Improve release process

---

README.md
examples/.gitignore
examples/simple-app/README.md
examples/simple-app/index.html
examples/simple-app/index.js
examples/simple-app/package.json

Add example application 
resolves #13

docs: Add example application

---

jest.config.js
lib/__mocks__/fileMock.js
lib/components/Layout/Header.js
stories/vrc-stories/Layout.js

Header value `name` undefined replace with `company`

Fix header undefined

---

.github/workflows/add-issue-to-project.yml

Add workflow to move issues to the current Kanban project if they are in the correct milestone

chore: add workflow to manage issues

---

lib/styles/build/css/design_tokens.css
lib/styles/build/js/design_tokens.js
lib/styles/style_dict/tokens/font/fonts.json

Due to postcss-custom-variables defect postcss/postcss-custom-properties#225

fix(design_tokens): add space between slash on font

---

examples/.eslintrc
lib/helpers/useMatchMedia.js

feat(use-match-media): support ssr

---

lib/helpers/useMatchMedia.js

fix(use-match-media): support ssr window undefined

---

LICENSE
package.json

per @pnancarrow's suggestion on behalf of @virtru

docs: move to MIT license

---

examples/simple-app/package.json
package.json

Remove contributors and update the references

chore: clean up package.json

---

.github/workflows/deploy-storybook.yml

Fix deploy-storybook

---

CHANGELOG.md
README.md

Chore redeploy 1.6.2 as 1.6.3 d

---

config/test.config.js
lib/components/Select/Select.css.js
lib/components/Select/Select.js
lib/components/Select/Select.test.js
package-lock.json
package.json
stories/vrc-stories/ChartContainer.js

changes: _rev_
- CCR-41
- Limited Select's max-height to 10 lines
- Added `isSearchable` prop to Chart container's Select component for it's Story

CCR-41: Make Chart container's Select searchable

---

lib/components/index.js

_Please ensure to label (via GitHub labels) the PR with either patch, minor, or major._
- CCR-44
- exported BarChart so that we can use it in the Control Center

fix: exported BarChart from components

---

lib/components/ChartContainer/ChartContainer.js
lib/components/Paginator/Paginator.js
lib/components/Paginator/components/Arrow/Arrow.js
lib/components/PieChart/components/ArcsLayer/ArcsLayer.js
lib/components/Table/Table.js
lib/components/Table/components/TD/TD.js
lib/components/Table/components/TH/TH.js
lib/components/Table/components/TR/TR.js

- CCR-124: Cypress tests
- add testIds to some virtuoso elements for testing
Load locally and see that various table and chart related elements now have `data-testids` prefixed with `VDS`

[CCR-124] chore: add data-testids to various elements

---

lib/components/PieChart/components/ArcsLayer/ArcsLayer.js

_Please ensure to label (via GitHub labels) the PR with either patch, minor, or major._
use better selector
build passes

fix: use better selector for pie element

---

.github/workflows/codeql-analysis.yml

_Please ensure to label (via GitHub labels) the PR with either patch, minor, or major._
- JIRAKEY-1234
- Some change

chore: add codeql analysis

---

lib/components/ChartContainer/ChartContainer.css
lib/components/ContentModal/ContentModal.css
lib/components/ContentModal/ContentModal.js

fix(contentmodal): z-index and data-testid - CCR-267

---

package.json

updated peer dependencies range for package

chore(deps): changed react, react-dom peer dependencies

---

lib/components/Table/Table.css
lib/components/Table/Table.js

- CCR-300
- Add fixed table layout

CCR-300 Add fixed table layout

---

package-lock.json
package.json

fix: revert auto major version

---

README.md

docs: explain install for create-react-apps

---

README.md
lib/components/table/table.css

- CCR-479
- improved styles for table

#CCR-479 improved styles for table

---

lib/components/dropdown/topMenuDropdown.css

- CCR-710
- Some changes in styles of top menu

#CCR-710 improve some styles

---

.eslintrc.js
CHANGELOG.md
lib/components/Layout/Header.css
lib/components/Layout/Header.js
lib/components/Layout/Header.test.js
lib/components/Layout/Layout.stories.js
package-lock.json
package.json

feat(header): added ability to wrap logo in header component

---

config/test.config.js
jest.config.js
lib/components/textEditor/linkStyles.css
lib/components/textEditor/richText.js
lib/components/textEditor/richText.test.js
package-lock.json
package.json

- CCR-960
- Tool bar buttons are not working as expected (link, alignment text, undo, redo buttons )

#CCR-960 Tool bar buttons are not working as expected

---

lib/components/fileListItem/fileListItem.css
lib/components/fileListItem/fileListItem.js

fix: warning icon

---

lib/components/expirationDate/expirationPicker.css

- CCR-955
- micro improve styles for expiration picker

#CCR-955 micro improve styles for expiration picker

---

lib/components/fileInput/fileInput.css
lib/components/fileInput/fileInput.js

- CCR-1095
- added focus state for attachment component

#CCR-1095 added focus state for attachment component

---

lib/components/arrowsNavigationWrap/arrowsNavigationWrap.js
lib/components/fileListItem/fileListItem.css
lib/components/fileListItem/fileListItem.js
lib/constans/keysMap.js
lib/index.js
stories/virtru/sendMessage/basic.jsx

- CCR-1094
- Added focus for whole item and navigation with arrows

#CCR-1094 Added focus for whole item and navigation with arrows

---

lib/components/expirationDate/expirationPicker.js

refactor(components): added the ability to set additional props

---

lib/components/expirationDate/expirationPicker.js
package-lock.json
package.json

fix(components/expiration-picker): fixing formatted string

---

lib/components/fileListItem/fileListItem.css
lib/components/fileListItem/fileListItem.js

Fixed FileListItem component

---

lib/components/layout/header.js

feat(header): add custom logo

---

lib/components/layout/header.js

fix(logo): size and spacing

---

lib/components/fileListItem/fileListItem.css

- CCR-1554
- Added min-height for cases when it does not have a size of the file

#CCR-1554 fix height for file item without size

---

lib/components/securitySettingsToggles/securitySettingsToggles.js

#CCR-1597 improve securitySettingsToggles

---

.eslintignore
.eslintrc.js
.gitignore
lib/components/infoTooltip/infoTooltip.js
stories/virtru/sendMessage/basic.jsx

#CCR-2013 add label role for tooltip btn

---

lib/components/textEditor/richText.js
stories/virtru/richText/basic.jsx

- [INT-389](https://virtru.atlassian.net/browse/INT-389)
[INT-389]: https://virtru.atlassian.net/browse/INT-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

INT-389: Fixed RichText state updating
